reactimail/message_template/urls.py
from django.urls import path
from . import views

app_name = "message_template"

urlpatterns = [
    path("add/", views.MessageTemplateCreateView.as_view(), name="add"),
    path("", views.MessageTemplateListView.as_view(), name="list"),
    path("<uuid:pk>/", views.MessageTemplateDetailView.as_view(), name="detail"),
    path("<uuid:pk>/edit/", views.MessageTemplateUpdateView.as_view(), name="edit"),
    path("<uuid:pk>/delete/", views.MessageTemplateDeleteView.as_view(), name="delete"),
]

reactimail/reactimail/urls.py
from django.contrib import admin
from django.urls import include, re_path, path

urlpatterns = [
    re_path(r"", include(("home.urls", "home"), namespace="home")),
    re_path(r"", include(("account.urls", "account"), namespace="account")),
    path("tags/", include("tag.urls", namespace="tag")),
    path(
        "message-templates/",
        include("message_template.urls", namespace="message_template"),
    ),
    path("admin/", admin.site.urls),
]

reactimail/tag/urls.py
from django.urls import path
from . import views

app_name = "tag"

urlpatterns = [
    path("add/", views.TagCreateView.as_view(), name="add"),
    path("", views.TagListView.as_view(), name="list"),
    path("<uuid:pk>/", views.TagDetailView.as_view(), name="detail"),
    path("<uuid:pk>/edit/", views.TagUpdateView.as_view(), name="edit"),
    path("<uuid:pk>/delete/", views.TagDeleteView.as_view(), name="delete"),
]

reactimail/message_template/models.py
import re
from string import Template

from django.db import models

from tag.models import Tag
from reactimail.models import BaseModelMixin

body_parameter_pattern = re.compile(r"\$\{(\w+)\}")


class MessageTemplateTypes(models.TextChoices):
    """The type of Email body."""

    TEXT = "text"
    HTML = "html"


class MessageTemplate(BaseModelMixin):

    TYPES = MessageTemplateTypes

    account = models.ForeignKey(
        "account.ReactiMailUser",
        on_delete=models.CASCADE,
        related_name="message_templates",
        verbose_name="Account",
        help_text="The account that owns this message template",
    )
    type = models.CharField(
        max_length=10,
        choices=TYPES.choices,
        verbose_name="Email Type",
        help_text="The type of the message (HTML or Text)",
    )
    title = models.CharField(
        max_length=200,
        verbose_name="Message Title",
        help_text="The title of the message template",
    )
    body = models.TextField(
        verbose_name="Message Body", help_text="The body of the message template"
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        related_name="message_templates",
        verbose_name="Tags",
        help_text="Tags associated with this message template",
    )

    @property
    def body_parameters(self) -> list[str]:
        tmpl = Template(self.body)
        return sorted(body_parameter_pattern.findall(tmpl.template))

    @property
    def tag_names(self) -> str:
        return ",".join(tag.name for tag in self.tags.order_by("name").all())

    def __str__(self):
        v = self.title
        if self.tag_names != "":
            v = v + f" (tags={self.tag_names})"
        return v

reactimail/message_template/forms.py
from string import Template
from re import compile

from django.forms import ModelForm, ValidationError
from .models import MessageTemplate

pattern = compile(r"\$\{(\w+)\}")


class MessageTemplateForm(ModelForm):
    class Meta:
        model = MessageTemplate
        fields = ["type", "title", "body", "tags"]

    def __init__(self, *args, **kwargs):
        # Capture the account from the view's context
        self.account = kwargs.pop("account", None)
        super().__init__(*args, **kwargs)

    def clean_body(self):
        body = self.cleaned_data.get("body")

        # Syntax checking and parameter extraction.
        try:
            tmpl = Template(body)
            parameters = pattern.findall(tmpl.template)
            # For checking the parameter list
            self.cleaned_data["parameters"] = parameters
        except ValueError as e:
            raise ValidationError(f"Template syntax error: {e}") from e

        return body

reactimail/message_template/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from .models import MessageTemplate
from .forms import MessageTemplateForm


class MessageTemplateCreateView(LoginRequiredMixin, CreateView):
    model = MessageTemplate
    form_class = MessageTemplateForm
    template_name = "message_template/form.html"
    success_url = reverse_lazy("message_template:list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["account"] = self.request.user  # Pass the account to the form
        return kwargs

    def form_valid(self, form):
        form.instance.account = self.request.user  # Set the account to the current user
        return super().form_valid(form)


class MessageTemplateListView(LoginRequiredMixin, ListView):
    model = MessageTemplate
    template_name = "message_template/list.html"

    def get_queryset(self):
        return MessageTemplate.objects.filter(account=self.request.user)


class MessageTemplateDetailView(LoginRequiredMixin, DetailView):
    model = MessageTemplate
    template_name = "message_template/detail.html"

    def get_queryset(self):
        return MessageTemplate.objects.filter(account=self.request.user)


class MessageTemplateUpdateView(LoginRequiredMixin, UpdateView):
    model = MessageTemplate
    form_class = MessageTemplateForm
    template_name = "message_template/form.html"
    success_url = reverse_lazy("message_template:list")

    def get_queryset(self):
        return MessageTemplate.objects.filter(account=self.request.user)


class MessageTemplateDeleteView(LoginRequiredMixin, DeleteView):
    model = MessageTemplate
    template_name = "message_template/confirm_delete.html"
    success_url = reverse_lazy("message_template:list")

    def get_queryset(self):
        return MessageTemplate.objects.filter(account=self.request.user)

reactimail/templates/message_template/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h2>Delete Message Template</h2>
<p>Are you sure you want to delete "{{ object.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a href="{% url 'message_template:list' %}">Cancel</a>
</form>
{% endblock %}

reactimail/templates/message_template/detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.title }}</h2>
<div>
    <strong>Type:</strong> {{ object.get_type_display }}
</div>
<div><strong>Body:</strong>
    <pre>{{ object.body }}</pre>
</div>
<div>
    <strong>Body Parameters:</strong>
    <ul>
        {% for body_parameter in object.body_parameters %}
        <li>{{ body_parameter }}</li>
        {% endfor %}
    </ul>
</div>
<div>
    <strong>Tags:</strong> {{ object.tag_names }}
</div>
<a href="{% url 'message_template:edit' object.pk %}">Edit</a>
<a href="{% url 'message_template:delete' object.pk %}">Delete</a>
<a href="{% url 'message_template:list' %}">Back to List</a>
{% endblock %}

reactimail/templates/message_template/form.html
{% extends "base.html" %}

{% block content %}
<h2>{% if object %}Edit{% else %}Add{% endif %} Message Template</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url 'message_template:list' %}">Back to List</a>
{% endblock %}

reactimail/templates/message_template/list.html
{% extends "base.html" %}

{% block content %}
<h2>Message Templates</h2>
<a href="{% url 'message_template:add' %}">Add New Message Template</a>
<ul>
    {% for template in object_list %}
    <li>
        <a href="{% url 'message_template:detail' template.pk %}">{{ template.title }}</a>
        <ul>
            {% for body_parameter in template.body_parameters %}
            <li>{{ body_parameter }}</li>
            {% endfor %}
        </ul>
        <a href="{% url 'message_template:edit' template.pk %}">Edit</a>
        <a href="{% url 'message_template:delete' template.pk %}">Delete</a>
    </li>
    {% empty %}
        <p>No message templates found.</p>
    {% endfor %}
</ul>
{% endblock %}