reactimail/reactimail/urls.py
from django.contrib import admin
from django.urls import include, re_path, path

urlpatterns = [
    re_path(r"", include(("home.urls", "home"), namespace="home")),
    re_path(r"", include(("account.urls", "account"), namespace="account")),
    path("tags/", include("tag.urls", namespace="tag")),
    path(
        "message-templates/",
        include("message_template.urls", namespace="message_template"),
    ),
    path("admin/", admin.site.urls),
]

reactimail/tag/urls.py
from django.urls import path
from . import views

app_name = "tag"

urlpatterns = [
    path("add/", views.TagCreateView.as_view(), name="add"),
    path("", views.TagListView.as_view(), name="list"),
    path("<uuid:pk>/", views.TagDetailView.as_view(), name="detail"),
    path("<uuid:pk>/edit/", views.TagUpdateView.as_view(), name="edit"),
    path("<uuid:pk>/delete/", views.TagDeleteView.as_view(), name="delete"),
]

reactimail/tag/models.py
from django.db import models

from reactimail.models import BaseModelMixin


class Tag(BaseModelMixin):
    account = models.ForeignKey(
        "account.ReactiMailUser",
        on_delete=models.CASCADE,
        related_name="tags",
        verbose_name="Account",
        help_text="The account that owns this tag",
    )
    name = models.CharField(
        max_length=200, verbose_name="Tag Name", help_text="The name of the tag"
    )

    class Meta:
        unique_together = ["account", "name"]
        ordering = ["name"]
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.name

reactimail/tag/forms.py
from django.forms import ModelForm, ValidationError
from .models import Tag


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        # Capture the account from the view's context
        self.account = kwargs.pop("account", None)
        super().__init__(*args, **kwargs)

    def clean_name(self) -> str:
        """
        Validate that the tag name is unique for the account.

        Returns:
            str: The validated tag name
        Raises:
            ValidationError: If a tag with the same name exists for the account
        """
        name = self.cleaned_data.get("name")
        existing_tags = Tag.objects.filter(account=self.account, name=name)
        if self.instance.id:
            existing_tags = existing_tags.exclude(id=self.instance.id)
        if existing_tags.exists():
            raise ValidationError(
                "A tag with this name already exists for your account."
            )
        return name

reactimail/tag/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import TagForm
from .models import Tag


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    form_class = TagForm
    template_name = "tag/form.html"
    success_url = reverse_lazy("tag:list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["account"] = self.request.user  # Pass the account to the form
        return kwargs

    def form_valid(self, form):
        form.instance.account = self.request.user  # Set the account to the current user
        return super().form_valid(form)


class TagListView(LoginRequiredMixin, ListView):
    model = Tag
    template_name = "tag/list.html"

    def get_queryset(self):
        # Filter tags by the logged-in user
        return Tag.objects.filter(account=self.request.user)


class TagDetailView(LoginRequiredMixin, DetailView):
    model = Tag
    template_name = "tag/detail.html"

    def get_queryset(self):
        # Ensure only tags belonging to the user can be edited
        return Tag.objects.filter(account=self.request.user)


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "tag/form.html"
    success_url = reverse_lazy("tag:list")

    def get_queryset(self):
        # Ensure only tags belonging to the user can be edited
        return Tag.objects.filter(account=self.request.user)


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = "tag/confirm_delete.html"
    success_url = reverse_lazy("tag:list")

    def get_queryset(self):
        # Ensure only tags belonging to the user can be deleted
        return Tag.objects.filter(account=self.request.user)

reactimail/templates/tag/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete Tag</h1>

<p>Are you sure you want to delete the tag "{{ object.name }}"?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'tag:list' %}">Cancel</a>
</form>

{% endblock %}

reactimail/templates/tag/detail.html
{% extends "base.html" %}

{% block content %}
<h1>Tag: {{ object.name }}</h1>

<a href="{% url 'tag:list' %}">Back to Tag List</a> |
<a href="{% url 'tag:edit' object.pk %}">Edit</a> |
<a href="{% url 'tag:delete' object.pk %}">Delete</a>

{% endblock %}

reactimail/templates/tag/form.html
{% extends "base.html" %}

{% block content %}
<h1>{% if object %}Edit Tag{% else %}Add New Tag{% endif %}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if form.non_field_errors %}
        <div class="error">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button type="submit">{% if object %}Update Tag{% else %}Create Tag{% endif %}</button>
</form>

<a href="{% url 'tag:list' %}">Back to Tag List</a>

{% endblock %}

reactimail/templates/tag/list.html
{% extends "base.html" %}

{% block content %}
<h1>Your Tags</h1>
<a href="{% url 'tag:add' %}">Add New Tag</a>

<ul>
    {% for tag in object_list %}
    <li>
        <a href="{% url 'tag:detail' tag.id %}">{{ tag.name }}</a>
        (<a href="{% url 'tag:edit' tag.id %}">Edit</a> |
        <a href="{% url 'tag:delete' tag.id %}">Delete</a>)
    </li>
    {% empty %}
    <p>No tags found.</p>
    {% endfor %}
</ul>

{% endblock %}